version: "3.9"

services:
  app:
    build: .
    image: it_tat_backend:latest
    container_name: it_tat_backend
    volumes:
      - static-data:/app/staticfiles
      - media-data:/app/media
    ports:
      - "127.0.0.1:8081:8000"   # faqat hostning localhost orqali kirish (host nginx proxy uchun)
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data:
