# backend/docker-compose.yml
version: "3.9"

services:
  app:
    build: .
    image: it_tat_backend:latest
    container_name: it_tat_backend
    volumes:
      - static-data:/app/staticfiles
      - media-data:/app/media
    restart: unless-stopped

    # faqat hostning localhost orqali ko'rinishi uchun 127.0.0.1:8081:8000
    ports:
      - "127.0.0.1:8081:8000"

    environment:
      - TZ=Asia/Tashkent
      # - DJANGO_SETTINGS_MODULE=config.settings.production (sizdan kelgan bo'lsa qo'shing)
    networks:
      - app-network

volumes:
  static-data:
  media-data:

networks:
  app-network:
    driver: bridge
