# Generated by Django 5.1.7 on 2025-03-27 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Kurs haqida ma'lumot")),
                ('duration_month', models.IntegerField(verbose_name='Kurs davomiyligi (oy)')),
                ('weekly_hours', models.IntegerField(verbose_name='Xafta davomiyligi (kun)')),
                ('duration_hours', models.IntegerField(verbose_name='Dars davomiyligi (soat)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Kurs rasmi')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kurs narxi (oylik)')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Chegirma(%)')),
                ('user_ai', models.BooleanField(blank=True, null=True, verbose_name='Kursda AI foydalaniladi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Savol')),
                ('description', models.TextField(verbose_name='Javob')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='ProgramRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': 'Dastur so‘rovi',
                'verbose_name_plural': 'Dastur so‘rovlari',
                'db_table': 'program_requests',
            },
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Mentor ismi')),
                ('last_name', models.CharField(max_length=255, verbose_name='Mentor familiyasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Mentor rasmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Mentor haqida ma'lumot")),
                ('experience', models.IntegerField(verbose_name='Mentor tajribasi (Yil)')),
                ('count_students', models.IntegerField(verbose_name='Mentorning mamnun studentlar soni')),
                ('courses', models.ManyToManyField(related_name='mentors', to='courses.courses', verbose_name='Kurslar')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentorlar',
                'db_table': 'mentors',
            },
        ),
        migrations.CreateModel(
            name='Feedback_Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Foydalanuvchi ismi')),
                ('video', models.FileField(blank=True, null=True, upload_to='feedback_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Fikr-mulohaza videosi')),
                ('feedback_text', models.TextField(blank=True, null=True, verbose_name='Izoh (matn shaklida)')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Kurs')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.mentors', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Mentor haqida fikr',
                'verbose_name_plural': 'Mentorlar haqida fikrlar',
                'db_table': 'feedback_mentor',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Portfolio nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Portfolio rasmi')),
                ('url', models.URLField(verbose_name='Portfolio linki')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Portfolio haqida ma'lumot")),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.mentors', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfoliolar',
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Ro‘yxatdan o‘tish',
                'verbose_name_plural': 'Ro‘yxatdan o‘tishlar',
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Texnologiya nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='technologies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Texnologiya rasmi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='courses.courses', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Texnologiya',
                'verbose_name_plural': 'Texnologiyalar',
                'db_table': 'technologies',
            },
        ),
    ]
