# Generated by Django 5.1.7 on 2025-03-28 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Kurs haqida ma'lumot")),
                ('duration_months', models.IntegerField(verbose_name='Kurs davomiyligi (oy)')),
                ('weekly_hours', models.IntegerField(verbose_name='Xaftalik dars (kun)')),
                ('duration_hours', models.IntegerField(verbose_name='Dars davomiyligi (soat)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp', 'svg'])], verbose_name='Kurs rasmi')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kursning narxi (oylik)')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Chegirma (%)')),
                ('uses_ai', models.BooleanField(blank=True, default=True, null=True, verbose_name='Kursda AI foydalaniladimi ?')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='title')),
                ('answer', models.TextField(verbose_name='Malumot')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Portfolio nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolios', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp', 'svg'])], verbose_name='Portfolio rasmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Portfolio haqida ma'lumot")),
                ('url', models.URLField(blank=True, null=True, verbose_name='Portfolio link')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='ProgramRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=17, unique=True)),
            ],
            options={
                'verbose_name': 'ProgramRequest',
                'verbose_name_plural': 'ProgramRequest',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Technoly/')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='CourseLessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dars nomi')),
                ('video', models.FileField(blank=True, null=True, upload_to='lesson_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'avi', 'mov', 'wmv', 'webm', 'flv'])], verbose_name='Video')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_videos', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiyasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentors', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp', 'svg'])], verbose_name='Mentor rasmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Mentor haqida ma'lumot")),
                ('experience_years', models.IntegerField(verbose_name='Tajriba (yil)')),
                ('students_count', models.IntegerField(verbose_name="Mentorning mamnun o'quvchilar soni")),
                ('courses', models.ManyToManyField(related_name='mentors', to='courses.course', verbose_name='Kurslar')),
                ('portfolios', models.ManyToManyField(related_name='mentors', to='courses.portfolio', verbose_name='Portfolios')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentorlar',
            },
        ),
        migrations.CreateModel(
            name='FeedbackMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Foydalanuvchi ismi')),
                ('video', models.FileField(blank=True, null=True, upload_to='feedback_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Fikr-mulohaza videosi')),
                ('feedback_text', models.TextField(blank=True, null=True, verbose_name='Izoh (matn shaklida)')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.mentor', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Mentor haqida fikr',
                'verbose_name_plural': 'Mentorlar haqida fikrlar',
                'db_table': 'feedback_mentor',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ismn')),
                ('phone_number', models.CharField(max_length=17, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registration',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(related_name='courses', to='courses.technology', verbose_name='Tehnologiyalar'),
        ),
    ]
