# Generated by Django 5.1.7 on 2025-03-25 05:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kurs haqida malumot')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Kurs rasmi')),
                ('weekly_hours', models.IntegerField(verbose_name='Haftalik dars davomiyligi(soat)')),
                ('duration_moths', models.IntegerField(verbose_name='Kurs davomiyligi(oy)')),
                ('total_hours', models.IntegerField(verbose_name='Umumiy dars davomiyligi(soat)')),
                ('price_per_moths', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narxi(oylik)')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chegrima(%)')),
                ('user_ai', models.BooleanField(blank=True, default=True, null=True, verbose_name='AI bilan ishlash')),
                ('start_hour', models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti(soat)')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentor_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Mentor rasmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mentor haqida malumot')),
                ('experience_years', models.IntegerField(verbose_name='Tajribasi(yil)')),
                ('student_count', models.IntegerField(verbose_name="O'quvchi soni")),
                ('courses', models.ManyToManyField(related_name='mentors', to='courses.course', verbose_name='Kurslar')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentorlar',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Portfolio nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Portfolio rasmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Portfolio haqida malumot')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Portfolio sahifasi linki')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='courses.mentor', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
