# Generated by Django 5.1.7 on 2025-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='course',
            name='weekly_hours',
            field=models.IntegerField(verbose_name='Xaftalik dars (kun)'),
        ),
    ]
