# Generated by Django 5.1.7 on 2025-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='portfolios',
            field=models.ManyToManyField(related_name='mentors', to='courses.portfolio', verbose_name='Portfolios'),
        ),
    ]
