# Generated by Django 5.1.7 on 2025-04-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_portfolio_mentor_mentor_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='portfolios',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentors', to='courses.portfolio', verbose_name='Portfolios'),
        ),
    ]
