# Generated by Django 5.1.7 on 2025-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_mentor_portfolios'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='achievements_count',
            field=models.IntegerField(default=0, verbose_name='Mentorning yutuqlar soni'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='projects_part_count',
            field=models.IntegerField(default=0, verbose_name='Mentorning qatnashgan loyihalar soni'),
        ),
    ]
