# Generated by Django 5.1.7 on 2025-06-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_mentor_achievements_count_mentor_projects_part_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
    ]
