# Generated by Django 5.1.7 on 2025-06-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_registration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='global_junior_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dunyo miqyosida Junior daraja oylik maosh (USD)'),
        ),
        migrations.AddField(
            model_name='course',
            name='global_middle_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dunyo miqyosida Middle daraja oylik maosh (USD)'),
        ),
        migrations.AddField(
            model_name='course',
            name='global_senior_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dunyo miqyosida Senior daraja oylik maosh (USD)'),
        ),
        migrations.AddField(
            model_name='course',
            name='uzb_junior_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="O'zbekistonda Junior daraja oylik maosh (USD)"),
        ),
        migrations.AddField(
            model_name='course',
            name='uzb_middle_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="O'zbekistonda Middle daraja oylik maosh (USD)"),
        ),
        migrations.AddField(
            model_name='course',
            name='uzb_senior_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="O'zbekistonda Senior daraja oylik maosh (USD)"),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='achievements_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Mentorning yutuqlar soni'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='projects_part_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Mentorning qatnashgan loyihalar soni'),
        ),
    ]
