# HTTP dan HTTPS ga redirect
server {
    listen 80;
    server_name ittat.uz www.ittat.uz;

    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name ittat.uz www.ittat.uz;

    # Maksimal so‘rov hajmini o‘rnatish
    client_max_body_size 600M;

    # SSL sertifikatlarni yo‘lini ko‘rsatish
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    # SSL sozlamalarini optimallashtirish
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # HSTS (HTTP Strict Transport Security) qo‘shish
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Statik fayllar
    location /static/ {
        alias /app/staticfiles/;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Media fayllar
    location /media/ {
        alias /app/media/;
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }

    # API so‘rovlarini DRF’ga yo‘naltirish
    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}